export const EXTRA_ACTIVITY_LIST = [
  { key: 1, label: "extra_activity_list.baseball_club" },
  { key: 2, label: "extra_activity_list.rub_baseball_club" },
  { key: 3, label: "extra_activity_list.american_football_club" },
  { key: 4, label: "extra_activity_list.soccer_club" },
  { key: 5, label: "extra_activity_list.tennis_club" },
  { key: 6, label: "extra_activity_list.track_club" },
  { key: 7, label: "extra_activity_list.kendo_club" },
  { key: 8, label: "extra_activity_list.judo_club" },
  { key: 9, label: "extra_activity_list.table_tennis_club" },
  { key: 10, label: "extra_activity_list.badminton_club" },
  { key: 11, label: "extra_activity_list.basket_club" },
  { key: 12, label: "extra_activity_list.music_club" },
  { key: 13, label: "extra_activity_list.science_depart" },
  { key: 14, label: "extra_activity_list.maths_depart" },
  { key: 15, label: "extra_activity_list.shogi_club" },
  { key: 16, label: "extra_activity_list.robot_division" },
  { key: 17, label: "extra_activity_list.broadcast_depart" },
  { key: 18, label: "extra_activity_list.perform_art_depart" },
  { key: 19, label: "extra_activity_list.theater_club" },
  { key: 20, label: "extra_activity_list.academic_club" },
  { key: 21, label: "extra_activity_list.vk_club" },
  { key: 22, label: "extra_activity_list.program_club" },
  { key: 23, label: "extra_activity_list.swim_club" },
  { key: 24, label: "extra_activity_list.railway_club" },
  { key: 25, label: "extra_activity_list.model_nation_club" },
  { key: 26, label: "extra_activity_list.art_club" },
]
