export const MOCK_MEAL_SKIP_DATA = [
  {
    id: 94301,
    affiliation: "-",
    target_number: 24,
    start_date: "4月7日 朝食",
    end_date: "4月10日 夕食",
    grade: 1,
    class: 1,
    house: "A",
    extra_activity: "硬式野球部",
  },
  {
    id: 94302,
    affiliation: "-",
    target_number: 24,
    start_date: "4月7日 朝食",
    end_date: "4月10日 夕食",
    grade: 1,
    class: 1,
    house: "A",
    extra_activity: "硬式野球部",
  },
  {
    id: 94303,
    affiliation: "-",
    target_number: 24,
    start_date: "4月7日 朝食",
    end_date: "4月10日 夕食",
    grade: 1,
    class: 1,
    house: "A",
    extra_activity: "硬式野球部",
  },
  {
    id: 94304,
    affiliation: "-",
    target_number: 24,
    start_date: "4月7日 朝食",
    end_date: "4月10日 夕食",
    grade: 1,
    class: 1,
    house: "A",
    extra_activity: "硬式野球部",
  },
  {
    id: 94305,
    affiliation: "-",
    target_number: 24,
    start_date: "4月7日 朝食",
    end_date: "4月10日 夕食",
    grade: 1,
    class: 1,
    house: "A",
    extra_activity: "硬式野球部",
  },
  {
    id: 94306,
    affiliation: "-",
    target_number: 24,
    start_date: "4月7日 朝食",
    end_date: "4月10日 夕食",
    grade: 1,
    class: 1,
    house: "A",
    extra_activity: "硬式野球部",
  },
  {
    id: 94307,
    affiliation: "-",
    target_number: 24,
    start_date: "4月7日 朝食",
    end_date: "4月10日 夕食",
    grade: 1,
    class: 1,
    house: "A",
    extra_activity: "硬式野球部",
  },
  {
    id: 94308,
    affiliation: "-",
    target_number: 24,
    start_date: "4月7日 朝食",
    end_date: "4月10日 夕食",
    grade: 1,
    class: 1,
    house: "A",
    extra_activity: "硬式野球部",
  },
  {
    id: 94309,
    affiliation: "-",
    target_number: 24,
    start_date: "4月7日 朝食",
    end_date: "4月10日 夕食",
    grade: 1,
    class: 1,
    house: "A",
    extra_activity: "硬式野球部",
  },
  {
    id: 94311,
    affiliation: "-",
    target_number: 24,
    start_date: "4月7日 朝食",
    end_date: "4月10日 夕食",
    grade: 1,
    class: 1,
    house: "A",
    extra_activity: "硬式野球部",
  },
  {
    id: 94312,
    affiliation: "-",
    target_number: 24,
    start_date: "4月7日 朝食",
    end_date: "4月10日 夕食",
    grade: 1,
    class: 1,
    house: "A",
    extra_activity: "硬式野球部",
  },
  {
    id: 94313,
    affiliation: "-",
    target_number: 24,
    start_date: "4月7日 朝食",
    end_date: "4月10日 夕食",
    grade: 1,
    class: 1,
    house: "A",
    extra_activity: "硬式野球部",
  },
  {
    id: 94314,
    affiliation: "-",
    target_number: 24,
    start_date: "4月7日 朝食",
    end_date: "4月10日 夕食",
    grade: 1,
    class: 1,
    house: "A",
    extra_activity: "硬式野球部",
  },
  {
    id: 94315,
    affiliation: "-",
    target_number: 24,
    start_date: "4月7日 朝食",
    end_date: "4月10日 夕食",
    grade: 1,
    class: 1,
    house: "A",
    extra_activity: "硬式野球部",
  },
  {
    id: 94316,
    affiliation: "-",
    target_number: 24,
    start_date: "4月7日 朝食",
    end_date: "4月10日 夕食",
    grade: 1,
    class: 1,
    house: "A",
    extra_activity: "硬式野球部",
  },
  {
    id: 94317,
    affiliation: "-",
    target_number: 24,
    start_date: "4月7日 朝食",
    end_date: "4月10日 夕食",
    grade: 1,
    class: 1,
    house: "A",
    extra_activity: "硬式野球部",
  },
]
