export const mockUploadData = [
  {
    page: 94301,
    fullName: "山田太郎",
    grade: 1,
    recipient: "生徒・保護者",
    status: "-",
  },
  {
    page: 94302,
    fullName: "山田太郎",
    grade: 1,
    recipient: "生徒・保護者",
    status: "-",
  },
  {
    page: 94303,
    fullName: "山田太郎",
    grade: 1,
    recipient: "生徒・保護者",
    status: "-",
  },
  {
    page: 94304,
    fullName: "山田太郎",
    grade: 1,
    recipient: "生徒・保護者",
    status: "-",
  },
  {
    page: 94305,
    fullName: "山田太郎",
    grade: 1,
    recipient: "生徒・保護者",
    status: "-",
  },
  {
    page: 94306,
    fullName: "山田太郎",
    grade: 1,
    recipient: "生徒・保護者",
    status: "-",
  },
  {
    page: 94307,
    fullName: "山田太郎",
    grade: 1,
    recipient: "生徒・保護者",
    status: "-",
  },
  {
    page: 94308,
    fullName: "山田太郎",
    grade: 1,
    recipient: "生徒・保護者",
    status: "-",
  },
  {
    page: 94309,
    fullName: "山田太郎",
    grade: 1,
    recipient: "生徒・保護者",
    status: "-",
  },
  {
    page: 94310,
    fullName: "山田太郎",
    grade: 1,
    recipient: "生徒・保護者",
    status: "-",
  },
  {
    page: 94311,
    fullName: "山田太郎",
    grade: 1,
    recipient: "生徒・保護者",
    status: "-",
  },
  {
    page: 94312,
    fullName: "山田太郎",
    grade: 1,
    recipient: "生徒・保護者",
    status: "-",
  },
  {
    page: 94313,
    fullName: "山田太郎",
    grade: 1,
    recipient: "生徒・保護者",
    status: "-",
  },
]
